### ISSUE TITLE
No docs of NFS shared volumes since 4 months

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/app-swarm-ui#3]
The note is still in README file:
NOTE: use of SwarmUI on a multi-node Swarm cluster requires shared volumes, like NFS. Specific documentation on setting this up will follow in the coming weeks.

**Comment by madnificent** [comment]
@earthquakesan The note is not in the current repository.  Please (re)open a ticket or send me an email if there should be a note in other repositories.  Thanks for the comments.
